GET http://localhost/slimroute/public/showList/drink/low
Accept: application/json

###
GET http://localhost/slimroute/public/showList/drink/low/50
Accept: application/json

###
GET http://localhost/slimroute/public/showDetail/abc
Accept: application/json

###
POST http://localhost/slimroute/public/helloMap
Content-Type: application/json

{}

###
GET http://localhost/slimroute/public/helloMap
Accept: application/json

###
POST http://localhost/slimroute/public/helloAny
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
GET http://localhost/slimroute/public/helloAny
Accept: application/json

###
GET http://localhost/slimroute/public/writeBody
Accept: application/json

###
GET http://localhost/slimroute/public/showParams?name=井谷&age=832
Accept: application/json

###
POST http://localhost/slimroute/public/showParams
Content-Type: application/x-www-form-urlencoded

name=井谷&age=19

###


