GET http://localhost/slimcontroller/public/constructor/helloWithContainer
Accept: application/json

###
GET http://localhost/slimcontroller/public/several/showSecond
Accept: application/json

###
GET http://localhost/slimcontroller/public/several/showFirst
Accept: application/json

###
